- name: Create databases
  vars:
    # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
    ansible_ssh_pipelining: true
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ item.name }}"
  with_items: "{{ postgresql_databases }}"
